require("mason-null-ls").setup({
    ensure_installed = { 
      "actionlint", 
      "prettierd",
      "alex",
      "buf",
      "codespell",
      "hadolint",
      "luacheck",
      "markdownlint",
      "protolint",
      "selene",
      "shellcheck",
      "vint",
      "yamllint",
      "cbfmt",
      "codespell",
      "fixjson",
    }
})
